name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          packages/bootstrap/package-lock.json
          packages/multiplayer-template/package-lock.json
    
    - name: Build and test
      run: |
        npm ci
        npm run build
        npm run test

    - name: Lint
      run: npm run lint

    - name: Typecheck bootstrap
      run: npm run typecheck
      working-directory: ./packages/bootstrap

    - name: npm link core locally
      run: |
        npm link
      working-directory: ./packages/core

    # multiplayer-template has its own nested workspaces (client/server) that npm
    # workspaces does not handle recursively, so we need a separate npm ci here
    - name: Build multiplayer-template
      run: |
        npm link @mavonengine/core
        npm run typecheck
        npm run build
        npm run lint
      working-directory: ./packages/multiplayer-template
